### ISSUE TITLE
python36：pip install python-gssapi==0.6.4 ERROR

### ISSUE THREAD

**Issue by GounGG** [sigmaris/python-gssapi#8]
version：python36
os：Centos 7.5
ERROR INFO:
```
[root@localhost requirements]# pip3 install python-gssapi
Collecting python-gssapi
  Using cached https://files.pythonhosted.org/packages/a4/9e/648b4e85235097edcee561c986f7075cb1606be24c514cfcdd2930e35c5e/python-gssapi-0.6.4.tar.gz
    Complete output from command python setup.py egg_info:
    running egg_info
    creating pip-egg-info/python_gssapi.egg-info
    writing pip-egg-info/python_gssapi.egg-info/PKG-INFO
    writing dependency_links to pip-egg-info/python_gssapi.egg-info/dependency_links.txt
    writing requirements to pip-egg-info/python_gssapi.egg-info/requires.txt
    writing top-level names to pip-egg-info/python_gssapi.egg-info/top_level.txt
    writing manifest file 'pip-egg-info/python_gssapi.egg-info/SOURCES.txt'
    Package gss was not found in the pkg-config search path.
    Perhaps you should add the directory containing `gss.pc'
    to the PKG_CONFIG_PATH environment variable
    No package 'gss' found
    gssapi/bindings/__pycache__/_cffi__x8e012de6x6c820412.c:212:27: fatal error: gssapi/gssapi.h: No such file or directory
     #include <gssapi/gssapi.h>
                               ^
    compilation terminated.
    gssapi/bindings/__pycache__/_cffi__xf223bac3xa79bfeef.c:212:27: fatal error: gssapi/gssapi.h: No such file or directory
     #include <gssapi/gssapi.h>
                               ^
    compilation terminated.
    gssapi/bindings/__pycache__/_cffi__xb3bc6629xdba4f2a1.c:212:27: fatal error: gssapi/gssapi.h: No such file or directory
     #include <gssapi/gssapi.h>
                               ^
    compilation terminated.
    gssapi/bindings/__pycache__/_cffi__xeb514d6x5d98e1c3.c:212:27: fatal error: gssapi/gssapi.h: No such file or directory
     #include <gssapi/gssapi.h>
                               ^
    compilation terminated.
    gssapi/bindings/__pycache__/_cffi__x67999e0x2a0d7c22.c:212:27: fatal error: gssapi/gssapi.h: No such file or directory
     #include <gssapi/gssapi.h>
                               ^
    compilation terminated.
    gssapi/bindings/__pycache__/_cffi__x680d8754xa883e720.c:212:27: fatal error: gssapi/gssapi.h: No such file or directory
     #include <gssapi/gssapi.h>
                               ^
    compilation terminated.
    gssapi/bindings/__pycache__/_cffi__x3116e390xdc4bc63b.c:212:27: fatal error: gssapi/gssapi.h: No such file or directory
     #include <gssapi/gssapi.h>
                               ^
    compilation terminated.
    gssapi/bindings/__pycache__/_cffi__x605c8c53xc4f5555d.c:212:27: fatal error: gssapi/gssapi.h: No such file or directory
     #include <gssapi/gssapi.h>
                               ^
    compilation terminated.
    gssapi/bindings/__pycache__/_cffi__xeb98ca96x39d25428.c:212:27: fatal error: gssapi/gssapi.h: No such file or directory
     #include <gssapi/gssapi.h>
                               ^
    compilation terminated.
    gssapi/bindings/__pycache__/_cffi__x9da3f28cxf7292814.c:212:27: fatal error: gssapi/gssapi.h: No such file or directory
     #include <gssapi/gssapi.h>
                               ^
    compilation terminated.
    gssapi/bindings/__pycache__/_cffi__x71c8306cx52487aa4.c:212:27: fatal error: gssapi/gssapi.h: No such file or directory
     #include <gssapi/gssapi.h>
                               ^
    compilation terminated.
    gssapi/bindings/__pycache__/_cffi__xcb5bccdbx18251cfe.c:212:27: fatal error: gssapi/gssapi.h: No such file or directory
     #include <gssapi/gssapi.h>
                               ^
    compilation terminated.
    gssapi/bindings/__pycache__/_cffi__xaa59ba48xdb9bd1d2.c:212:27: fatal error: gssapi/gssapi.h: No such file or directory
     #include <gssapi/gssapi.h>
                               ^
    compilation terminated.
    Traceback (most recent call last):
      File "/usr/lib64/python3.6/distutils/unixccompiler.py", line 127, in _compile
        extra_postargs)
      File "/usr/lib64/python3.6/distutils/ccompiler.py", line 909, in spawn
        spawn(cmd, dry_run=self.dry_run)
      File "/usr/lib64/python3.6/distutils/spawn.py", line 36, in spawn
        _spawn_posix(cmd, search_path, dry_run=dry_run)
      File "/usr/lib64/python3.6/distutils/spawn.py", line 159, in _spawn_posix
        % (cmd, exit_status))
    distutils.errors.DistutilsExecError: command 'gcc' failed with exit status 1
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "/usr/local/lib64/python3.6/site-packages/cffi/ffiplatform.py", line 51, in _build
        dist.run_command('build_ext')
      File "/usr/lib64/python3.6/distutils/dist.py", line 974, in run_command
        cmd_obj.run()
      File "/usr/local/lib/python3.6/site-packages/setuptools/command/build_ext.py", line 78, in run
        _build_ext.run(self)
      File "/usr/lib64/python3.6/distutils/command/build_ext.py", line 339, in run
        self.build_extensions()
      File "/usr/lib64/python3.6/distutils/command/build_ext.py", line 448, in build_extensions
        self._build_extensions_serial()
      File "/usr/lib64/python3.6/distutils/command/build_ext.py", line 473, in _build_extensions_serial
        self.build_extension(ext)
      File "/usr/local/lib/python3.6/site-packages/setuptools/command/build_ext.py", line 199, in build_extension
        _build_ext.build_extension(self, ext)
      File "/usr/lib64/python3.6/distutils/command/build_ext.py", line 533, in build_extension
        depends=ext.depends)
      File "/usr/lib64/python3.6/distutils/ccompiler.py", line 574, in compile
        self._compile(obj, src, ext, cc_args, extra_postargs, pp_opts)
      File "/usr/lib64/python3.6/distutils/unixccompiler.py", line 129, in _compile
        raise CompileError(msg)
    distutils.errors.CompileError: command 'gcc' failed with exit status 1
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-por0lx0f/python-gssapi/setup.py", line 74, in <module>
        url="https://github.com/sigmaris/python-gssapi",
      File "/usr/local/lib/python3.6/site-packages/setuptools/__init__.py", line 143, in setup
        return distutils.core.setup(**attrs)
      File "/usr/lib64/python3.6/distutils/core.py", line 148, in setup
        dist.run_commands()
      File "/usr/lib64/python3.6/distutils/dist.py", line 955, in run_commands
        self.run_command(cmd)
      File "/usr/lib64/python3.6/distutils/dist.py", line 974, in run_command
        cmd_obj.run()
      File "/usr/local/lib/python3.6/site-packages/setuptools/command/egg_info.py", line 296, in run
        self.find_sources()
      File "/usr/local/lib/python3.6/site-packages/setuptools/command/egg_info.py", line 303, in find_sources
        mm.run()
      File "/usr/local/lib/python3.6/site-packages/setuptools/command/egg_info.py", line 534, in run
        self.add_defaults()
      File "/usr/local/lib/python3.6/site-packages/setuptools/command/egg_info.py", line 570, in add_defaults
        sdist.add_defaults(self)
      File "/usr/local/lib/python3.6/site-packages/setuptools/command/py36compat.py", line 34, in add_defaults
        self._add_defaults_python()
      File "/usr/local/lib/python3.6/site-packages/setuptools/command/sdist.py", line 127, in _add_defaults_python
        build_py = self.get_finalized_command('build_py')
      File "/usr/lib64/python3.6/distutils/cmd.py", line 299, in get_finalized_command
        cmd_obj.ensure_finalized()
      File "/usr/lib64/python3.6/distutils/cmd.py", line 107, in ensure_finalized
        self.finalize_options()
      File "/usr/local/lib/python3.6/site-packages/setuptools/command/build_py.py", line 34, in finalize_options
        orig.build_py.finalize_options(self)
      File "/usr/lib64/python3.6/distutils/command/build_py.py", line 45, in finalize_options
        ('force', 'force'))
      File "/usr/lib64/python3.6/distutils/cmd.py", line 287, in set_undefined_options
        src_cmd_obj.ensure_finalized()
      File "/usr/lib64/python3.6/distutils/cmd.py", line 107, in ensure_finalized
        self.finalize_options()
      File "/tmp/pip-install-por0lx0f/python-gssapi/setup.py", line 22, in finalize_options
        self.distribution.ext_modules = get_ext_modules()
      File "/tmp/pip-install-por0lx0f/python-gssapi/setup.py", line 15, in get_ext_modules
        from gssapi.bindings import ffi
      File "/tmp/pip-install-por0lx0f/python-gssapi/gssapi/__init__.py", line 4, in <module>
        from . import bindings
      File "/tmp/pip-install-por0lx0f/python-gssapi/gssapi/bindings/__init__.py", line 233, in <module>
        C = ffi.verify(_source, **_kwargs)
      File "/usr/local/lib64/python3.6/site-packages/cffi/api.py", line 451, in verify
        lib = self.verifier.load_library()
      File "/usr/local/lib64/python3.6/site-packages/cffi/verifier.py", line 104, in load_library
        self._compile_module()
      File "/usr/local/lib64/python3.6/site-packages/cffi/verifier.py", line 201, in _compile_module
        outputfilename = ffiplatform.compile(tmpdir, self.get_extension())
      File "/usr/local/lib64/python3.6/site-packages/cffi/ffiplatform.py", line 22, in compile
        outputfilename = _build(tmpdir, ext, compiler_verbose, debug)
      File "/usr/local/lib64/python3.6/site-packages/cffi/ffiplatform.py", line 58, in _build
        raise VerificationError('%s: %s' % (e.__class__.__name__, e))
    cffi.error.VerificationError: CompileError: command 'gcc' failed with exit status 1
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-install-por0lx0f/python-gssapi/
```

**Comment by guoxu3** [comment]
@GounGG yum install -y krb5-devel

**Comment by DavideyLee** [comment]
mac上也报同样的错误

**Comment by GounGG** [comment]
> @GounGG yum install -y krb5-devel

可以解决问题

**Comment by RocsSun** [comment]
> > @GounGG yum install -y krb5-devel
> 
> 可以解决问题

Windows下呢，折腾了好久，把包下载下来安装不上
